---

title: My KIT Homepage

fullname: Max Mustermann
institute: Institute of ...
campus: Campus Sued
building: 30.23
street: Musterstrasse 24
phone: 0721 1234567
mail: max.mustermann@kit.edu

startpage:
    file: start
    title: Homepagetitle

navigation:
    - file: start
      title: Startseite
      order: 1
    - file: example
      title: Example Page
      order: 2


showboxes: true
infobox:
    - title: Example-Box
      text: |
          A simple list
          <ul>
          <li>item 1</li>
          <li>another item</li>
          <li>third item</li>
          </ul>
    - title: "{{fullname}}"
      text: |
            Karlsruher Institut f&uuml;r Technologie<br />
            {{institute}}<br />
            {{campus}}, Geb. {{building}}<br />
            {{street}}<br />
            76131 Karlsruhe<br />
            E-Mail: <a href='mailto:{{mail}}'>{{mail}}</a><br />
            Phone: {{phone}}
