---

title: My KIT Homepage

mail: max.mustermann@kit.edu

startpage:
    file: start
    title: Homepagetitle

headernavigation:
    - title: HOME
      href: '#start'
      order: 1
    - title: IMPRESSUM
      href: 'https://www.kit.edu/impressum.php'
      order: 2
    - title: KIT
      href: 'https://www.kit.edu'
      order: 3


navigation:
    - file: start
      title: Startseite
      order: 1
    - file: example
      title: Example Page
      order: 2


showboxes: true
infobox:
    - title: Example-Box
      text: |
          <div class="markdown">
          A simple list
            * item 1
            * another item
            * third item
          </div>
    - title: "Prof. Dr. Mustermann"
      text: |
            <div class="markdown">
            Beispielinstitut (BI) 
               
            Campus S&uuml;d  
            Geb. 30.23, 11/12  
            Wolfgang-Gaede-Strasse 1  
            76131 Karlsruhe 
               
            [{{mail}}](mailto:{{mail}})
            </div>

root_templates:
    - .htaccess
